import StyleDictionary from 'style-dictionary';
import { flatCamel, hexToSwiftColor } from './swift.js';

const ROOT = 'Color';

// Order leaves alphabetically by their flattened Swift identifier, so output
// is stable and `ThemeColorsProtocol` / concrete `Colors` / `ThemeColor` /
// switch arms all share the same case ordering.
const sortLeaves = (tokens) =>
  tokens
    .map((t) => ({
      token: t,
      ident: flatCamel(t.path),
      hex: hexToSwiftColor(t.$value ?? t.value),
    }))
    .sort((a, b) => a.ident.localeCompare(b.ident));

const formatProtocol = (leaves) => {
  const props = leaves.map((l) => `    var ${l.ident}: UIColor { get }`);
  const cases = leaves.map((l) => `    case ${l.ident}`);
  const arms = leaves.map((l) => `        case .${l.ident}: ${l.ident}`);
  return [
    '// Generated by Style Dictionary. Do not edit by hand.',
    '// Naming: JSON dotted paths camelCased — `fg.primary` → `fgPrimary`,',
    '// `bg.surface.main` → `bgSurfaceMain`, `avatar.bg.amethyst` → `avatarBgAmethyst`.',
    '',
    'import UIKit',
    '',
    'public protocol ThemeColorsProtocol {',
    ...props,
    '',
    '    func color(_ color: ThemeColor) -> UIColor',
    '}',
    '',
    'public enum ThemeColor: String, Hashable, CaseIterable {',
    ...cases,
    '}',
    '',
    'public extension ThemeColorsProtocol {',
    '    func color(_ color: ThemeColor) -> UIColor {',
    '        switch color {',
    ...arms,
    '        }',
    '    }',
    '}',
    '',
  ].join('\n');
};

const formatConcreteTheme = (leaves, theme) => {
  const lets = leaves.map((l) => `        public let ${l.ident} = ${l.hex}`);
  return [
    '// Generated by Style Dictionary. Do not edit by hand.',
    '',
    'import UIKit',
    '',
    `public final class ${theme.className}: CommonTheme {`,
    '    public init() {',
    '        super.init(',
    `            id: "${theme.selectionKey}",`,
    `            systemStyle: .${theme.systemStyle},`,
    `            statusBarStyle: .${theme.statusBarStyle},`,
    '            colors: Colors()',
    '        )',
    '    }',
    '',
    '    public final class Colors: ThemeColorsProtocol {',
    ...lets,
    '    }',
    '}',
    '',
  ].join('\n');
};

const formatSelection = (themes) => {
  const cases = themes.map((t) => `    case ${t.selectionKey}`);
  return [
    '// Generated by Style Dictionary. Do not edit by hand.',
    '// `rawValue` is the theme id (matches `Theme.id`) and serves as the persistence key.',
    '',
    'public enum ThemeSelection: String, Codable, CaseIterable, Hashable {',
    ...cases,
    '}',
    '',
  ].join('\n');
};

const formatRegistry = (themes, defaults) => {
  const factories = themes.map(
    (t, i) =>
      `        .${t.selectionKey}: ${t.className}.init${i < themes.length - 1 ? ',' : ''}`
  );
  return [
    '// Generated by Style Dictionary. Do not edit by hand.',
    '// Adding a new theme = the generator appends one entry to `factories` and,',
    '// when the new theme is marked as the default for its system style in',
    '// $themes.json, updates `defaultLightSelection` / `defaultDarkSelection`.',
    '',
    'public enum ThemesRegistry {',
    '    public static let factories: [ThemeSelection: () -> Theme] = [',
    ...factories,
    '    ]',
    '',
    `    public static let defaultDarkSelection: ThemeSelection = .${defaults.dark}`,
    `    public static let defaultLightSelection: ThemeSelection = .${defaults.light}`,
    '',
    '    public static func makeTheme(_ selection: ThemeSelection) -> Theme {',
    `        (factories[selection] ?? ${themes[0].className}.init)()`,
    '    }',
    '}',
    '',
  ].join('\n');
};

export const register = () => {
  StyleDictionary.registerFormat({
    name: 'swift/theme-colors-protocol',
    format: ({ dictionary }) => {
      const semantic = dictionary.allTokens.filter((t) => t.path[0] !== ROOT);
      return formatProtocol(sortLeaves(semantic));
    },
  });

  StyleDictionary.registerFormat({
    name: 'swift/theme-colors-concrete',
    format: ({ dictionary, options }) => {
      const semantic = dictionary.allTokens.filter((t) => t.path[0] !== ROOT);
      return formatConcreteTheme(sortLeaves(semantic), options.theme);
    },
  });

  StyleDictionary.registerFormat({
    name: 'swift/theme-selection',
    format: () => formatSelection(themes),
  });

  StyleDictionary.registerFormat({
    name: 'swift/themes-registry',
    format: () =>
      formatRegistry(themes, {
        dark: themes.find((t) => t.systemStyle === 'darkAppearance')?.selectionKey ?? themes[0].selectionKey,
        light: themes.find((t) => t.systemStyle === 'lightAppearance')?.selectionKey ?? themes[0].selectionKey,
      }),
  });
};

export const primitivesSource = 'source/Color Primitives/Values.json';
export const outputDir = 'out/ios/';
export const themes = [
  {
    source: 'source/Theme/Polkadot App Default.json',
    className: 'PolkadotDefaultTheme',
    selectionKey: 'polkadotDefault',
    file: 'Themes/PolkadotDefaultTheme.swift',
    systemStyle: 'darkAppearance',
    statusBarStyle: 'lightContent',
  },
];
