import StyleDictionary from 'style-dictionary';
import { camel, isReference } from '../../lib/utils.js';
import { fontFamilySlug, fontWeightExpr } from './swift.js';

const THEME_ROOT = 'Typescale';

// Match the iOS template's role + size ordering. Role order is Display → Headline →
// Title → Paragraph → Body → Label → Emoji (Paragraph before Body, opposite of
// Compose). Sizes are descending: ExtraLarge → Large → Medium → Small → Tiny.
const ROLE_ORDER = ['Display', 'Headline', 'Title', 'Paragraph', 'Body', 'Label', 'Emoji'];
const SIZE_ORDER = ['ExtraLarge', 'Large', 'Medium', 'Small', 'Tiny'];

const orderIndex = (list, item) => {
  const i = list.indexOf(item);
  return i < 0 ? list.length : i;
};

// Re-derive the per-entry property bag from raw tokens. Mirrors the byEntry
// loop in lib/typography-analysis.js but keeps the raw entries (the iOS
// template emits one Typescale case per source entry, not per variant).
const buildEntries = (themeTokens) => {
  const byName = new Map();
  for (const t of themeTokens) {
    if (t.path[0] !== THEME_ROOT) continue;
    const entryName = t.path[1];
    const prop = t.path[2];
    const ref = t.original.$value ?? t.original.value;
    const resolved = t.$value ?? t.value;
    if (!byName.has(entryName)) byName.set(entryName, {});
    byName.get(entryName)[prop] = { ref, resolved };
  }
  return byName;
};

const isBroken = (entry) =>
  entry === undefined || (isReference(entry.ref) && entry.resolved === entry.ref);

// "Display ExtraLarge" -> { role: "Display", size: "ExtraLarge" }
const splitName = (name) => {
  const idx = name.indexOf(' ');
  if (idx < 0) return { role: name, size: '' };
  return { role: name.slice(0, idx), size: name.slice(idx + 1) };
};

const sortedEntries = (byName) => {
  const arr = [];
  for (const [name, props] of byName.entries()) {
    const missing = ['font', 'weight', 'size', 'lineHeight'].filter((k) => isBroken(props[k]));
    if (missing.length > 0) {
      arr.push({ name, props, broken: missing });
      continue;
    }
    if (isBroken(props.tracking)) props.tracking = { ref: '0', resolved: 0 };
    const { role, size } = splitName(name);
    arr.push({ name, props, role, size });
  }
  // Skip broken before sorting (they don't have role/size).
  const valid = arr.filter((e) => !e.broken);
  const skipLog = arr
    .filter((e) => e.broken)
    .map((e) => `  - ${e.name}: missing/unresolved ${e.broken.join(', ')}`);
  valid.sort((a, b) => {
    const r = orderIndex(ROLE_ORDER, a.role) - orderIndex(ROLE_ORDER, b.role);
    if (r !== 0) return r;
    return orderIndex(SIZE_ORDER, a.size) - orderIndex(SIZE_ORDER, b.size);
  });
  return { entries: valid, skipLog };
};

const specCase = (entry) => {
  const caseName = camel(entry.name);
  const family = `.${fontFamilySlug(entry.props.font.resolved)}`;
  const monoFamily = !isBroken(entry.props.fontMono)
    ? `.${fontFamilySlug(entry.props.fontMono.resolved)}`
    : null;
  const weight = fontWeightExpr(entry.props.weight);
  const emphasizedWeight = !isBroken(entry.props.weightEmphasized)
    ? fontWeightExpr(entry.props.weightEmphasized)
    : null;
  const size = entry.props.size.resolved;
  const lineHeight = entry.props.lineHeight.resolved;
  const tracking = entry.props.tracking.resolved;

  const fields = [['family', family]];
  if (monoFamily) fields.push(['monoFamily', monoFamily]);
  fields.push(['size', size]);
  fields.push(['weight', weight]);
  if (emphasizedWeight) fields.push(['emphasizedWeight', emphasizedWeight]);
  fields.push(['lineHeight', lineHeight]);
  fields.push(['tracking', tracking]);

  const multiline = monoFamily !== null || emphasizedWeight !== null;
  if (!multiline) {
    const args = fields.map(([k, v]) => `${k}: ${v}`).join(', ');
    return `        case .${caseName}: .init(${args})`;
  }
  const lines = fields.map(
    ([k, v], i) => `                ${k}: ${v}${i < fields.length - 1 ? ',' : ''}`
  );
  return [
    `        case .${caseName}: .init(`,
    ...lines,
    '            )',
  ].join('\n');
};

const formatTypescale = (entries) => {
  const cases = entries.map((e) => `        case ${camel(e.name)}`);
  const specs = entries.map(specCase);

  // Group static factories by role with a blank line between groups.
  const staticGroups = [];
  let lastRole = null;
  for (const e of entries) {
    if (e.role !== lastRole) {
      if (staticGroups.length > 0) staticGroups.push('');
      lastRole = e.role;
    }
    const c = camel(e.name);
    staticGroups.push(`    static var ${c}: TypographyStyle { .init(typescale: .${c}) }`);
  }

  return [
    '// Generated by Style Dictionary. Do not edit by hand.',
    'import CoreGraphics',
    '',
    'public extension TypographyStyle {',
    '    enum Typescale: String, CaseIterable, Hashable {',
    ...cases,
    '    }',
    '}',
    '',
    'public extension TypographyStyle.Typescale {',
    '    var spec: TypographyStyleSpec {',
    '        switch self {',
    ...specs,
    '        }',
    '    }',
    '}',
    '',
    'public extension TypographyStyle {',
    ...staticGroups,
    '}',
    '',
  ].join('\n');
};

const formatSelection = (families) => {
  const cases = families.map((f) => `    case ${f.selectionKey}`);
  return [
    '// Generated by Style Dictionary. Do not edit by hand.',
    '// `rawValue` is the family id (matches `TypographyFamily.id`) and serves as the',
    '// persistence key.',
    '',
    'public enum TypographySelection: String, Codable, CaseIterable, Hashable {',
    ...cases,
    '}',
    '',
  ].join('\n');
};

const formatRegistry = (families) => {
  const factories = families.map(
    (f, i) =>
      `        .${f.selectionKey}: ${f.className}.init${i < families.length - 1 ? ',' : ''}`
  );
  return [
    '// Generated by Style Dictionary. Do not edit by hand.',
    '// Adding a new typography family = generator appends one entry to `factories`.',
    '',
    'public enum TypographyFamiliesRegistry {',
    '    public static let factories: [TypographySelection: () -> TypographyFamily] = [',
    ...factories,
    '    ]',
    '',
    `    public static let \`default\`: TypographySelection = .${families[0].selectionKey}`,
    '',
    '    public static func makeFamily(_ selection: TypographySelection) -> TypographyFamily {',
    `        (factories[selection] ?? ${families[0].className}.init)()`,
    '    }',
    '}',
    '',
  ].join('\n');
};

export const register = () => {
  StyleDictionary.registerFormat({
    name: 'swift/typography-typescale',
    format: ({ dictionary }) => {
      const themeTokens = dictionary.allTokens.filter((t) => t.path[0] === THEME_ROOT);
      const { entries, skipLog } = sortedEntries(buildEntries(themeTokens));
      if (skipLog.length > 0) {
        console.log('\n[swift typography] Skipped:');
        for (const line of skipLog) console.log(line);
      }
      return formatTypescale(entries);
    },
  });

  StyleDictionary.registerFormat({
    name: 'swift/typography-selection',
    format: () => formatSelection(families),
  });

  StyleDictionary.registerFormat({
    name: 'swift/typography-families-registry',
    format: () => formatRegistry(families),
  });
};

export const primitivesSource = 'source/Number Primitives/Values.json';
export const outputDir = 'out/ios/';
export const families = [
  {
    source: 'source/Typography/Polkadot App Default.json',
    className: 'PolkadotDefaultTypography',
    selectionKey: 'polkadotDefault',
  },
];
